# -*- coding: utf-8 -*-
"""Untitled.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U5ACIcs4OISXshxQEqfHqrPQCHWdoqjW
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

data1 = pd.read_csv("/content/drive/My Drive/data1.csv")

data2 = pd.read_csv("/content/drive/My Drive/data2.csv")

data1.head()

data2.head()

"""data1 preprocessing phase

"""

data1.info()

data2.info()

data2.isnull().sum()

data1['habit'].nunique()



data1.dropna(subset=['habit'], inplace=True)

data1.info()

data1['risk'] = data1['risk'].astype(int)

reward_rat = data1.groupby('risk')['reward'].mean()
reward_rat

"""lets perform chi square test for dependency in risk and reward
* H0 : Risk  and reward are independent
* H1  : risk taking and reward are dependent
"""

from scipy.stats import chi2_contingency

contingence = pd.crosstab(data1['risk'], data1['reward'])
_,p_value,_,_= chi2_contingency(contingence)

print(p_value)

"""p value is ~ 0 so hypothesis 1 is valid"""

plt.figure(figsize=(6,4))
sns.boxplot(x=data1['risk'], y=data1['seconds_after_rat_arrival'])
plt.title("Seconds after Rat Arrival vs Risk Behaviour")
plt.xlabel("Risk Behaviour (0=Avoid, 1=Risk-Taking)")
plt.ylabel("Seconds after Rat Arrival")
plt.show()

correlation = data2['rat_minutes'].corr(data2['bat_landing_number'])
print("Correlation", correlation)

"""The negative correlation indicatee, more the rat stays less the landing occurs as shown in
scatter plot.
The above chi square sujject the dependency on risk and reward
this support the idea that the bats percive the rats as a potentail predators.
"""

